import { Inter } from 'next/font/google';
import './globals.css';
import styles from './layout.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'SecurePod',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          SeCUREpod{' '}
          <Link href="/login" className={styles.login}>
            Log in
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
